### ISSUE TITLE
Use Commitizen commits style

### ISSUE THREAD

**Issue by KnupMan** [ybaidiuk/internotes#2]
For better and readable commit messages I'd propose to use https://github.com/commitizen/cz-cli style. No need to use exactly the CLI, but just use the keywords as a commit indicator.
Here is the keywords with explanations:
![image](https://user-images.githubusercontent.com/16997074/39839695-b371270e-53e5-11e8-8869-5a5b1ffcb542.png)

**Comment by ybaidiuk** [comment]
i not sure i we wo really have to use it . every single developer can use it himself. 
i working with intellij embedded graphical  version control.
