### ISSUE TITLE
Use linter tools (Prettier + ESlint)

### ISSUE THREAD

**Issue by KnupMan** [ybaidiuk/internotes#3]
To have the same code style at the repo I'd propose to use ESlint with Prettier to solve the problem.
Also, to not make it difficult, we can try Husky for pre-commit stuff for linting.

**Comment by KnupMan** [comment]
https://github.com/eslint/eslint
https://github.com/prettier/prettier
https://github.com/typicode/husky

**Comment by ybaidiuk** [comment]
now code style is not a problem . probably later if more developers will work here we will add it)
