### ISSUE TITLE
Setup CI for Builds and Tests

### ISSUE THREAD

**Issue by KnupMan** [ybaidiuk/internotes#4]
For automatic builds and tests would be great to setup CI tool (e.g. CircleCI).

**Comment by KnupMan** [comment]
Here is a great demo how to setup CircleCI with React Native: https://github.com/CircleCI-Public/circleci-demo-react-native
Unfortunately, seems like I don't have a permissions to setup `internotes` app within the Circle, so maybe @ybaidiuk you can look at this one.
![image](https://user-images.githubusercontent.com/16997074/39843738-2c72b136-53f5-11e8-8e5d-9b56069b5360.png)

So what will be the benefits - you don't need to test both iOS and Android for the working app, it will be done by the CI.

**Comment by ybaidiuk** [comment]
@KnupMan  i will try to do it in next few weeks.
